=== paulomenezes/text-mining/cogroo-4.0.0-src/cogroo-4.0.0-src/cogroo-gc/src/main/resources/error_report/ErrorReport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2012 cogroo <cogroo@cogroo.org>

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:extensionBindingPrefixes="xjc" jaxb:version="2.0">


    <xs:complexType name="Omission">
    	<xs:sequence>
    		<xs:element name="Category" type="xs:string" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="CustomCategory" type="xs:string"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
            <xs:element name="ReplaceBy" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="Comment" type="xs:string" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="Span" type="Span" maxOccurs="1"
    			minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="BadIntervention">
    	<xs:sequence>
    		<xs:element name="Classification" maxOccurs="1"
    			minOccurs="1">
    			<xs:simpleType>
    				<xs:annotation>
    					<xs:appinfo>
    						<jaxb:typesafeEnumClass
    							name="BadInterventionClassification" />
    					</xs:appinfo>
    				</xs:annotation>
    				<xs:restriction base="xs:string">
    					<xs:enumeration value="falseError" />
    					<xs:enumeration
    						value="inappropriateDescription" />
    					<xs:enumeration value="inappropriateSuggestion" />
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="Comment" type="xs:string" maxOccurs="1"
    			minOccurs="0">
    		</xs:element>
    		<xs:element name="Rule" type="xs:string" maxOccurs="1"
    			minOccurs="1">
    		</xs:element>
    		<xs:element name="Span" type="Span" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Span">
    	<xs:sequence>
    		<xs:element name="Start" type="xs:int"></xs:element>
    		<xs:element name="End" type="xs:int"></xs:element>
    	</xs:sequence>
    </xs:complexType>



    <xs:complexType name="IgnoreError">
    	<xs:sequence>
    		<xs:element name="Span" type="Span" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="Rule" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:element name="ErrorReport">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="Version" type="xs:string"
    				maxOccurs="1" minOccurs="1">
    			</xs:element>
    			<xs:element name="Text" type="xs:string" maxOccurs="1"
    				minOccurs="1">
    			</xs:element>
				<xs:element name="BadInterventions"
					maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element
								name="BadIntervention" type="BadIntervention"
								maxOccurs="unbounded" minOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Omissions" maxOccurs="1"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Omission"
								type="Omission" maxOccurs="unbounded" minOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
</xs:schema>

=== paulomenezes/text-mining/cogroo-4.0.0-src/cogroo-4.0.0-src/cogroo-gc/src/test/resources/org/cogroo/errorreport/ErrorReport1.xml
<ErrorReport xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ErrorReport.xsd">
	<Version>3.0.0</Version>
    <Text>Fomos levados à crer. Os menino são burros de doer.</Text>
    <BadInterventions>
        <BadIntervention>
            <Classification>falseError</Classification>
            <Comment>Um falso erro</Comment>f
            <Rule>xml:4</Rule>
            <Span>
                <Start>14</Start>
                <End>15</End>
            </Span>
        </BadIntervention>
        <BadIntervention>
            <Classification>inappropriateDescription</Classification>
            <Comment>uma di</Comment>
            <Rule>xml:95</Rule>
            <Span>
                <Start>22</Start>
                <End>31</End>
            </Span>
        </BadIntervention>
    </BadInterventions>
    <Omissions>
        <Omission>
            <Category>Colocação pronominal</Category>
            <ReplaceBy>nada</ReplaceBy>
            <Comment>Não é nada</Comment>
            <Span>
                <Start>6</Start>
                <End>13</End>
            </Span>
        </Omission>
        <Omission>
            <CustomCategory>fdfsd</CustomCategory>
            <ReplaceBy>Blah blah</ReplaceBy>
            <Comment>Um comantário</Comment>
            <Span>
                <Start>32</Start>
                <End>42</End>
            </Span>
        </Omission>
	</Omissions>
</ErrorReport>
